// Code generated by MockGen. DO NOT EDIT.
// Source: schema.go
//
// Generated by this command:
//
//	mockgen -source=schema.go -destination=../mocks/mockschema/schema_mock.go -package mockschema
//

// Package mockschema is a generated GoMock package.
package mockschema

import (
	context "context"
	reflect "reflect"

	schema "github.com/effective-security/xdb/schema"
	gomock "go.uber.org/mock/gomock"
)

// MockHasTableInfo is a mock of HasTableInfo interface.
type MockHasTableInfo struct {
	ctrl     *gomock.Controller
	recorder *MockHasTableInfoMockRecorder
	isgomock struct{}
}

// MockHasTableInfoMockRecorder is the mock recorder for MockHasTableInfo.
type MockHasTableInfoMockRecorder struct {
	mock *MockHasTableInfo
}

// NewMockHasTableInfo creates a new mock instance.
func NewMockHasTableInfo(ctrl *gomock.Controller) *MockHasTableInfo {
	mock := &MockHasTableInfo{ctrl: ctrl}
	mock.recorder = &MockHasTableInfoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHasTableInfo) EXPECT() *MockHasTableInfoMockRecorder {
	return m.recorder
}

// GetTableInfo mocks base method.
func (m *MockHasTableInfo) GetTableInfo() *schema.TableInfo {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTableInfo")
	ret0, _ := ret[0].(*schema.TableInfo)
	return ret0
}

// GetTableInfo indicates an expected call of GetTableInfo.
func (mr *MockHasTableInfoMockRecorder) GetTableInfo() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTableInfo", reflect.TypeOf((*MockHasTableInfo)(nil).GetTableInfo))
}

// MockProvider is a mock of Provider interface.
type MockProvider struct {
	ctrl     *gomock.Controller
	recorder *MockProviderMockRecorder
	isgomock struct{}
}

// MockProviderMockRecorder is the mock recorder for MockProvider.
type MockProviderMockRecorder struct {
	mock *MockProvider
}

// NewMockProvider creates a new mock instance.
func NewMockProvider(ctrl *gomock.Controller) *MockProvider {
	mock := &MockProvider{ctrl: ctrl}
	mock.recorder = &MockProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProvider) EXPECT() *MockProviderMockRecorder {
	return m.recorder
}

// ListForeignKeys mocks base method.
func (m *MockProvider) ListForeignKeys(ctx context.Context, schemaNames, tableNames []string) (schema.ForeignKeys, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListForeignKeys", ctx, schemaNames, tableNames)
	ret0, _ := ret[0].(schema.ForeignKeys)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListForeignKeys indicates an expected call of ListForeignKeys.
func (mr *MockProviderMockRecorder) ListForeignKeys(ctx, schemaNames, tableNames any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListForeignKeys", reflect.TypeOf((*MockProvider)(nil).ListForeignKeys), ctx, schemaNames, tableNames)
}

// ListTables mocks base method.
func (m *MockProvider) ListTables(ctx context.Context, schemaNames, tableNames []string, withDependencies bool) (schema.Tables, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTables", ctx, schemaNames, tableNames, withDependencies)
	ret0, _ := ret[0].(schema.Tables)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTables indicates an expected call of ListTables.
func (mr *MockProviderMockRecorder) ListTables(ctx, schemaNames, tableNames, withDependencies any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTables", reflect.TypeOf((*MockProvider)(nil).ListTables), ctx, schemaNames, tableNames, withDependencies)
}

// ListViews mocks base method.
func (m *MockProvider) ListViews(ctx context.Context, schemaNames, tableNames []string) (schema.Tables, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListViews", ctx, schemaNames, tableNames)
	ret0, _ := ret[0].(schema.Tables)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListViews indicates an expected call of ListViews.
func (mr *MockProviderMockRecorder) ListViews(ctx, schemaNames, tableNames any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListViews", reflect.TypeOf((*MockProvider)(nil).ListViews), ctx, schemaNames, tableNames)
}

// Name mocks base method.
func (m *MockProvider) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockProviderMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockProvider)(nil).Name))
}
